name: sign_button
description: A Flutter plugin for generating sign in buttons for different social media accounts.
version: 4.0.0
homepage: https://github.com/samu-developments/Flutter-Sign-in-Button-1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
     - images/

